CREATE TABLE person
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName    VARCHAR(100) NOT NULL,
    yearOfBirth INT          NOT NULL CHECK ( yearOfBirth > 1900 AND yearOfBirth < 2024 )
);

CREATE TABLE book
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT          REFERENCES person (id) ON DELETE SET NULL,
    title     VARCHAR(100) NOT NULL,
    author    VARCHAR(100) NOT NULL,
    year      INT          NOT NULL CHECK ( year > 0 and year < 2024 )
);

INSERT INTO person(fullname, yearofbirth)
VALUES ('Иванов Иван Иванович', 1970);
INSERT INTO person(fullname, yearofbirth)
VALUES ('Петров Петр Петрович', 1960);
INSERT INTO person(fullname, yearofbirth)
VALUES ('Алексеев Алексей Алексеевич', 1989);
INSERT INTO person(fullname, yearofbirth)
VALUES ('Познер Владимир Владимирович', 1944);
INSERT INTO person(fullname, yearofbirth)
VALUES ('Федоров Мирон Янович', 1985);

INSERT INTO book(person_id, title, author, year)
VALUES (1, 'Над пропастью во ржи', 'Джером Селинджер', 1951);
INSERT INTO book(person_id, title, author, year)
VALUES (2, 'День опричника', 'Владимир Сорокин', 2006);
INSERT INTO book(person_id, title, author, year)
VALUES (3, 'Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
INSERT INTO book(person_id, title, author, year)
VALUES (4, 'Философия Джава', 'Брюс Эккель', 2018);
INSERT INTO book(person_id, title, author, year)
VALUES (5, 'Психопаталогия обыденной жизни', 'Фрейд Зигмунд', 1904);
INSERT INTO book(person_id, title, author, year)
VALUES (5, 'Игра в бисер', 'Герман Гессе', 1943);
INSERT INTO book(person_id, title, author, year)
VALUES (5, 'Бытие и время', 'Мартин Хайдеггер', 1927);